### ISSUE TITLE
Which version of 1.16.5?

### ISSUE THREAD

**Issue by mikepoullas** [alcatrazEscapee/mcjunitlib#10]
Hello Again.

So I decided to drop to version of 1.16.5 to be able to use the 1.16 of the library but I'm having issues when running the build.gradle
I downloaded version 1.16.5-36.2.27 of the MDK and the error I get:

"Apply build file "build.gradle" to root project 'forge-1.16.5-36.2.27-mdk" shows a RED circle

The line that seems to be causing it is the testImplementation fg.deobf here:

    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    	testImplementation fg.deobf('com.github.alcatrazEscapee:mcjunitlib:1.16.5_1.4.4')
	}
Any suggestions? Also should I be using a specific MDK?

Thanks so much.

**Comment by mikepoullas** [comment]
Ok, so I changed the tag to be: 
    	testImplementation fg.deobf('com.github.alcatrazEscapee:mcjunitlib:1.4.4-1.16.5')

* What went wrong:
A problem occurred evaluating root project 'forge-1.16.5-36.2.27-mdk'.
> Could not get unknown property 'fg' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Same error. :(

**Comment by alcatrazEscapee** [comment]
You're putting the dependency in the `buildscript` dependencies block, don't do that. See an [example of where you **should** put it](https://github.com/alcatrazEscapee/no-tree-punching/blob/46682d0a26ece9a408e79db560a208d8cb405bde/build.gradle#L135) and an [example of where **not** to put it](https://github.com/alcatrazEscapee/no-tree-punching/blob/46682d0a26ece9a408e79db560a208d8cb405bde/build.gradle#L14)

**Comment by mikepoullas** [comment]
Genius!

Thank you SO much.

:)
