### ISSUE TITLE
How do I get runServerTest working?

### ISSUE THREAD

**Issue by mikepoullas** [alcatrazEscapee/mcjunitlib#11]
I created the ExampleTest.java
and its in the src/test/java folder. 
When I RUNAS Junit Test, the run fails with Java.lan.ExceptionInitilaizerError.

I don't see (or know how) to get runServerTest working.

When I RUNCONFIGURATIONS runClient it starts MC no problem but I don't see anything
The Console does not display anything about  [Server thread/UNITTEST]

**Comment by alcatrazEscapee** [comment]
Can you stop using the issue tracker as a place for basic tech support? I have a [discord](https://discord.gg/EWx23XqsRq) for that express purpose...

**Comment by mikepoullas** [comment]
Yes of course. My apologize.
