### ISSUE TITLE
No tests found?

### ISSUE THREAD

**Issue by robotgryphon** [alcatrazEscapee/mcjunitlib#5]
I've been trying to update some previous tests on https://github.com/CompactMods/CompactCrafting and no matter which version I try, it appears the JUnit discoverer is stopping or not discovering any of my test classes.

The classpath directories appear correct, and it looks like the prerequisite builds and combinations of my API lib and main code are all there.. so I'm lost. 

Things I've attempted, with no luck:
- Tried the original version, 1.3.3 in the file
- Tried to update to 1.4.1
- Tried to update to 1.4.3
- Tried regenerating the run configs and running in debug (several times)
- Tried adding and removing the `targetModId` environment line
- Tried adding `sourceSets.test` (and main/api) under `mods { compactcrafting {  } }`
- Tried several variations of the README unit tests config
- Tried removing the `destinationDir` from the JAR tasks

**Comment by alcatrazEscapee** [comment]
Interesting. Two things come of note:
- Change the logging level from `unittest` to `debug` (helpful if you're doing any debugging as the unittest log level can hide some actual errors).
- What is the log output (at debug level) for this line?
```
Found supplied mod coordinates [some stuff should be here]
```

That should match the classpath roots that are being passed into the JUnit test discover-er, that's my first place I'd check.

**Comment by robotgryphon** [comment]
Tried doing just that while troubleshooting, actually. I didn't see anything particularly obvious in the log, it just completed with nothing found.. also, the coords did look correct (paths were fine, classes were built there).

I'll try poking at it a bit more, see if I can't get a log to attach here shortly. Thanks.

**Comment by robotgryphon** [comment]
[Here are the debug and latest log files from the unit test run.](https://gist.github.com/robotgryphon/fd6c23c71ce11adac9db161ce8743993)

Updated to 1.4.3 and regenerated everything before the run, just to make sure it was the latest version. The most interesting thing I notice is the modlauncher "Current naming domain is 'mcp'" line.

Much further down (formatted with extra lines for easy reading):
```
[02Sep2021 14:53:19.145] [Server thread/DEBUG] [UnitTests/]: Found supplied mod coordinates [[
  D:\compact-crafting\build\resources\main, 
  D:\compact-crafting\build\classes\java\test, 
  D:\compact-crafting\build\resources\api, 
  D:\compact-crafting\build\resources\test, 
  D:\compact-crafting\build\classes\java\api, 
  D:\compact-crafting\build\classes\java\main
]]
[02Sep2021 14:53:19.743] [Server thread/UNITTEST] [UnitTests/]: Did not discover any tests to run.
```

So it definitely looks like it's picking up all three modules (api, main, and test) as well.
